# Generated by Django 4.2.5 on 2024-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="DefaultBrand", max_length=255),
        ),
    ]
