# Generated by Django 4.2.5 on 2024-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_app", "0003_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("both", "Both")],
                default="both",
                max_length=6,
            ),
        ),
    ]
